---
apiVersion: v1
kind: Application
metadata:
  name: NGINX-App
  labels:
   autor: Anil
   name: Proxy
spec:
  source:
    repoURL: https://github.com/AnilGitSpace/K8s.git
    targetRevision: HEAD
    path: ./
 destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

  containers:
   - name: webserver
     image: nginx
---
