---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: Anil
    type: Proxy
spec:
  containers:
   - name: webserver
     image: nginx
  source:
   repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
   targetRevision: HEAD
   path: dev
  destination: 
   server: https://kubernetes.default.svc
   namespace: myapp
   ---
