---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: Anil
    type: Proxy
spec:
 source:
    repoURL: https://github.com/AnilGitSpace/K8s.git
    targetRevision: HEAD
 destination:
    server: https://kubernetes.default.svc
    namespace: myapp
 containers:
   - name: webserver
     image: nginx
syncPolicy:
 syncOptions:
   - CreateNamespace=true

automated:
 selfHeal: true
 prune: true
--
