---
apiVersion: argoproj.io/v1alpha1
kind: Application1
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: Anilkumar
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
---
